
name: Java Self Practice
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REGISTRY: docker.io/${{ secrets.DOCKERHUB_USERNAME }}
      IMAGE_NAME: github-action-snapshot
      IMAGE_TAG: latest


    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn clean install

    - name: Login to dockerhub
      uses: docker/login-action@v3
      with:
       username: ${{ secrets.DOCKERHUB_USERNAME}}
       password: ${{ secrets.DOCKERHUB_TOKEN}}

      # Build the Docker image
    - name: Build Docker Image
      run: docker build -t  $REGISTRY/$IMAGE_NAME:$IMAGE_TAG .

      # Push the Docker image to Docker Hub
    - name: Push Docker Image
      run: docker push  $REGISTRY/$IMAGE_NAME:$IMAGE_TAG







  
